default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

# development:
#   <<: *default
#   database: nibi_development

# test:
#   <<: *default
#   database: nibi_test

# production:
#   <<: *default
#   database: nibi_production
#   username: nibi
#   password: nibi
development:
  <<: *default
  database: nibi_development
  host: db
  username: root
  password: aaaa1234
